# This configuration file is for the **development** setup.
# For a production example please refer to setup/docker-compose.yml.
version: '3.4'
x-redash-service: &redash-service
  build: .
  depends_on:
    - redis
  env_file: .env
  restart: always
#  volumes:
#    - ".:/app"

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries,scheduled_queries,schemas"
      WORKERS_COUNT: 2
  redis:
    image: redis:3-alpine
    restart: unless-stopped
