# This configuration file is for the **development** setup.
# For a production example please refer to setup/docker-compose.yml.
version: '3.4'
x-redash-service: &redash-service
  build:
    context: .
    args:
      skip_ds_deps: "yes"
      skip_override_pip_conf: "${REDASH_SKIP_OVERRIDE_PIP_CONF}"
  depends_on:
    - redis
  env_file: .env
  restart: always
  volumes:
    - ".:/app"

services:
  server:
    <<: *redash-service
    command: dev_server
    ports:
      - "5001:5000"
#  scheduler:
#    <<: *redash-service
#    command: scheduler
#    environment:
#      QUEUES: "celery"
#      WORKERS_COUNT: 1
  worker:
    <<: *redash-service
    command: dev_worker
    environment:
      QUEUES: "queries,scheduled_queries,celery,schemas"
      WORKERS_COUNT: 1
  redis:
    image: redis:3-alpine
    restart: unless-stopped
